[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = 'Unite'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
on_event = 'InsertEnter'
on_ft = 'snippet'
hook_source = 'source ~/.vim/scripts/plugins/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
  let g:neocomplete#enable_at_startup = 1
  source ~/.vim/scripts/plugins/neocomplete.vim
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  source ~/.vim/config/plugins/deoplete.vim
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'jsx', 'javascript.jsx']
hook_source = '''
let g:user_emmet_install_global = 0

let g:user_emmet_settings = {
\  'javascript.jsx' : {
\      'extends' : 'jsx',
\  },
\}

let g:user_emmet_leader_key='<C-Z>'
autocmd FileType html,css,jsx,javascript.jsx EmmetInstall
'''

# HTML5 ominicomplete & syntax
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'htmldjango']

# CSS3 syntax
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

# for vim-jsx
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

# React JSX
[[plugins]]
repo = 'mxw/vim-jsx'
depends = ['vim-javascript']
on_ft = ['jsx', 'javascript.jsx']

# React snippets
[[plugins]]
repo = 'justinj/vim-react-snippets'
on_ft = 'javascript.jsx'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'gabrielelana/vim-markdown'
on_ft = 'markdown'

