---
- hosts: localhost
  connection: local
  become: no

  tasks:

    - name: Update homebrew itself first
      homebrew: update_homebrew=yes

    - name: Install homebrew packages using homebrew-bundle
      shell: brew bundle | tee logs/brew_bundle.log

    - name: Link gcc@7
      file: src={{ item.src }} dest={{ item.dest }} state=link
      with_items:
        - src: /usr/local/bin/gcc-7
          dest: /usr/local/bin/gcc
        - src: /usr/local/bin/g++-7
          dest: /usr/local/bin/g++
        - src: /usr/local/bin/c++-7
          dest: /usr/local/bin/c++

    - name: Link iTerm2 config file
      file:
        src: ~/dotfiles/iterm/profiles.json
        dest: ~/Library/Application Support/iTerm2/DynamicProfiles/profiles.json

  handlers:
    - name: Run fc-cache
      shell: fc-cache -vf
