---
- hosts: localhost
  connection: local
  become: no

  roles:
    - role: zzet.rbenv
      rbenv:
        env: user
        default_ruby: 2.4.1
        rubies:
          - version: 2.4.1
            env:
              RUBY_CONFIGURE_OPTS: "--with-readline-dir=/usr/local/opt --with-openssl-dir=/usr/local/opt"

  tasks:
    - name: Install global gems
      gem: name={{ item }}
      with_items:
        - bundler
