---
- hosts: localhost
  connection: local
  become: yes

  vars:
    texlive_bin: /usr/local/texlive/2017/bin/x86_64-darwin

  tasks:

    - name: Clear log file
      file:
        state: absent
        path: logs/tlmgr.log

    - name: Update TeX packages
      shell: |
        {{ texlive_bin }}/tlmgr update --self --all 2>&1 | tee -a logs/tlmgr.log

    - name: Reflect updates
      shell: |
        cd `{{ texlive_bin }}/kpsewhich -var-value=TEXMFLOCAL`
        {{ texlive_bin }}/mktexlsr
